version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: agri-intel-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: .
    container_name: agri-intel-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongodb:27017/agri-intel
      JWT_SECRET: ${JWT_SECRET} # Uses the secret from your .env file
    depends_on:
      - mongodb
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  mongodb_data: